import Header from "@/components/header/header";
import { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "../../app/globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import ContactsPage from "./contacts/page";
import Cookies from "@/components/cookies/Cookies";
import Form from "@/components/form/Form";
import Contacts from "@/components/form/Contacts";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Tedalini Consalting LTD",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();

  return (
    <html lang={locale} className={inter.className}>
      <body>
        <Header />
        <main>
          <NextIntlClientProvider messages={messages}>
            <Cookies />
            {children}
          </NextIntlClientProvider>
        </main>
        {/* <Form locale = {locale}/> */}
        <Contacts locale = {locale}/>
        <Footer />
      </body>
    </html>
  );
}
